// Generated by Wrangler by running `wrangler types --env=production --no-include-runtime --no-strict-vars` (hash: 58f35d5b72cd52158fd12f3e81288591)
declare namespace Cloudflare {
	interface Env {
		BUN_VERSION: string;
		DISABLE_INVIS_CHARS_ENDPOINT: string;
		SECRET: string;
		InvisCharsDB: D1Database;
	}
}
interface Env extends Cloudflare.Env {}
