name = "sme"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-11-11"


[env.production.vars]
BUN_VERSION = "1.2.5"
DISABLE_INVIS_CHARS_ENDPOINT = ""

[[env.production.d1_databases]]
database_id = "3283ab35-cbc0-4d36-8674-2aeeb4dc6d47"
binding = "InvisCharsDB"
database_name = "InvisCharsDB"
# Required for Pages local development
preview_database_id = "InvisCharsDB"
